spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hmsdb
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true

jwt:
  algorithm:
    key: testingabcdefghijklmnopqrstuvwxyz
  issuer: sayali
  expiry:
    duration: 86400000


